; Auto-generated. Do not edit!


(cl:in-package franka_gripper-msg)


;//! \htmlinclude GraspFeedback.msg.html

(cl:defclass <GraspFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass GraspFeedback (<GraspFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GraspFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GraspFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name franka_gripper-msg:<GraspFeedback> is deprecated: use franka_gripper-msg:GraspFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GraspFeedback>) ostream)
  "Serializes a message object of type '<GraspFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GraspFeedback>) istream)
  "Deserializes a message object of type '<GraspFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GraspFeedback>)))
  "Returns string type for a message object of type '<GraspFeedback>"
  "franka_gripper/GraspFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GraspFeedback)))
  "Returns string type for a message object of type 'GraspFeedback"
  "franka_gripper/GraspFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GraspFeedback>)))
  "Returns md5sum for a message object of type '<GraspFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GraspFeedback)))
  "Returns md5sum for a message object of type 'GraspFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GraspFeedback>)))
  "Returns full string definition for message of type '<GraspFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GraspFeedback)))
  "Returns full string definition for message of type 'GraspFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GraspFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GraspFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'GraspFeedback
))
