; Auto-generated. Do not edit!


(cl:in-package franka_gripper-msg)


;//! \htmlinclude HomingGoal.msg.html

(cl:defclass <HomingGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass HomingGoal (<HomingGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <HomingGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'HomingGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name franka_gripper-msg:<HomingGoal> is deprecated: use franka_gripper-msg:HomingGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <HomingGoal>) ostream)
  "Serializes a message object of type '<HomingGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <HomingGoal>) istream)
  "Deserializes a message object of type '<HomingGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<HomingGoal>)))
  "Returns string type for a message object of type '<HomingGoal>"
  "franka_gripper/HomingGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'HomingGoal)))
  "Returns string type for a message object of type 'HomingGoal"
  "franka_gripper/HomingGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<HomingGoal>)))
  "Returns md5sum for a message object of type '<HomingGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'HomingGoal)))
  "Returns md5sum for a message object of type 'HomingGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<HomingGoal>)))
  "Returns full string definition for message of type '<HomingGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'HomingGoal)))
  "Returns full string definition for message of type 'HomingGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <HomingGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <HomingGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'HomingGoal
))
