; Auto-generated. Do not edit!


(cl:in-package franka_gripper-msg)


;//! \htmlinclude HomingFeedback.msg.html

(cl:defclass <HomingFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass HomingFeedback (<HomingFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <HomingFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'HomingFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name franka_gripper-msg:<HomingFeedback> is deprecated: use franka_gripper-msg:HomingFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <HomingFeedback>) ostream)
  "Serializes a message object of type '<HomingFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <HomingFeedback>) istream)
  "Deserializes a message object of type '<HomingFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<HomingFeedback>)))
  "Returns string type for a message object of type '<HomingFeedback>"
  "franka_gripper/HomingFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'HomingFeedback)))
  "Returns string type for a message object of type 'HomingFeedback"
  "franka_gripper/HomingFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<HomingFeedback>)))
  "Returns md5sum for a message object of type '<HomingFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'HomingFeedback)))
  "Returns md5sum for a message object of type 'HomingFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<HomingFeedback>)))
  "Returns full string definition for message of type '<HomingFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'HomingFeedback)))
  "Returns full string definition for message of type 'HomingFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <HomingFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <HomingFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'HomingFeedback
))
