; Auto-generated. Do not edit!


(cl:in-package franka_gripper-msg)


;//! \htmlinclude StopFeedback.msg.html

(cl:defclass <StopFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass StopFeedback (<StopFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StopFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StopFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name franka_gripper-msg:<StopFeedback> is deprecated: use franka_gripper-msg:StopFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StopFeedback>) ostream)
  "Serializes a message object of type '<StopFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StopFeedback>) istream)
  "Deserializes a message object of type '<StopFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StopFeedback>)))
  "Returns string type for a message object of type '<StopFeedback>"
  "franka_gripper/StopFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StopFeedback)))
  "Returns string type for a message object of type 'StopFeedback"
  "franka_gripper/StopFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StopFeedback>)))
  "Returns md5sum for a message object of type '<StopFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StopFeedback)))
  "Returns md5sum for a message object of type 'StopFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StopFeedback>)))
  "Returns full string definition for message of type '<StopFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StopFeedback)))
  "Returns full string definition for message of type 'StopFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StopFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StopFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'StopFeedback
))
