; Auto-generated. Do not edit!


(cl:in-package franka_gripper-msg)


;//! \htmlinclude StopGoal.msg.html

(cl:defclass <StopGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass StopGoal (<StopGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StopGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StopGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name franka_gripper-msg:<StopGoal> is deprecated: use franka_gripper-msg:StopGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StopGoal>) ostream)
  "Serializes a message object of type '<StopGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StopGoal>) istream)
  "Deserializes a message object of type '<StopGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StopGoal>)))
  "Returns string type for a message object of type '<StopGoal>"
  "franka_gripper/StopGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StopGoal)))
  "Returns string type for a message object of type 'StopGoal"
  "franka_gripper/StopGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StopGoal>)))
  "Returns md5sum for a message object of type '<StopGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StopGoal)))
  "Returns md5sum for a message object of type 'StopGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StopGoal>)))
  "Returns full string definition for message of type '<StopGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StopGoal)))
  "Returns full string definition for message of type 'StopGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StopGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StopGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'StopGoal
))
